org: defaultdev
service: foodiary-api

provider:
    name: aws
    region: us-east-1
    runtime: nodejs22.x
    memorySize: 128
    profile: dev.cloud
    stage: ${opt:stage, 'dev'}
    environment: ${file(./sls/config/env.yml)}

package:
    individually: true

build:
    esbuild:
        configFile: ./esbuild.config.mjs

functions:
    - ${file(./sls/functions/auth.yml)}

resources:
    - ${file(./sls/resources/UserPool.yml)}
