export enum ErrorCode {
    VALIDATION = "VALIDATION",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    BAD_REQUEST = "BAD_REQUEST",
    EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
}
